
TARGET: Cityscapes
NUM_WORKERS: 4
EXP_NAME: 'UNKNOWN_TASK'
DATA_DIRECTORY: '/home/yiren/cityscapes_numpy'
TRAIN:
  INPUT_SIZE: [512, 256]
  MODEL: FCN8s
  OPTIMIZER: 'SGD'
  SCHEDULER: 'step'
  LEARNING_RATE: 0.0001
  WEIGHT_DECAY: 0.0001
  MAX_ITERS: 150000
  EARLY_STOP: 150000
TEST:
  INPUT_SIZE: [512, 256]
  OUTPUT_SIZE: [512, 256]
  MODE: best
  MODEL:
    - FCN8s
  SNAPSHOT_MAXITER: 150000
